### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by GuiltySpark101** [sorrentmutie/SharpComicVine#1]
Hi there,

I was trying your API today and noticed it's not working anymore. When access the ComicVine API, a 403 error is given
![capture](https://cloud.githubusercontent.com/assets/19151405/14956780/c79ac194-1081-11e6-9766-565611d3639c.PNG)

The attached screenshot shows the error.
I've tried this from Windows 8.1 and Windows 10, the error remains there.

Could you have a look at this please ?

Thanks :)

**Comment by sorrentmutie** [comment]
Hi! Thanks for the warning! It seems that some migration is going on (http://comicvine.gamespot.com/user/migrate). We need to wait for some officiale new release and then (i hope) making few changes.

**Comment by GuiltySpark101** [comment]
Hi, The link you provided goes to the homepage, not sure what you're referring to. I'll post on the dev forum of CV to see what's going on.

**Comment by sorrentmutie** [comment]
Did you try opening the request link in the browser? 
For my key it's working but the request is redirect to the new address

http://comicvine.gamespot.com/api/volumes/?api_key=xxxxxxxxxxxxxxxxxxxxx&format=json&field_list=id,name,publisher&filter=name:The%20Amazing%20Spider-Man
 I don't know why in the console application the request is forbidden.
Any idea?

**Comment by GuiltySpark101** [comment]
No sorry, I don't have clue. I tried setting the UserAgent property but that doesn't seem to be a property anymore of the webRequest method (I hope I use the terms correctly, I'm not a developer, only trying to be one :) )

But, the issue is not in your code, it's definitely on the CV side.

**Comment by GuiltySpark101** [comment]
Apparently, CV changed some stuff on their but didn't communicate it properly, see this: http://comicvine.gamespot.com/forums/api-developers-2334/api-403-forbidden-message-1769849/#6
This text in particular:
__Hey guys. Yeah this was intentional. CBS is cracking down on bots and anonymous bots are no longer allowed. Your user agent must not be anything like "curl, perl, php, PyhonLib, wget" nor empty. Just provide a user agent preferably one that describes who you are and you'll be fine. This helps us too because we can pull reports on what you're doing and maybe find ways to make the API better for your particular use case.

Sorry the communication on this sucked..._ _

It seems they now block anonymous traffic and according to the info above, the UserAgent Property has to be set.

I tried to add it to the code but HttpWebRequest doesn't have a UserAgent Property which it should have according to Microsoft.

Could you check this and see if you're able to add the UserAgent Propery.

Thanks !

**Comment by sorrentmutie** [comment]
I solved the problem adding an User-Agent to the Request.
